version: '3.8'

services:
  ced-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ced-webapp
    restart: always
    ports:
      - "${DOCKER_APP_PORT}:${DOCKER_APP_PORT}"
    env_file:
      - .env.local
    networks:
      - ced-network

networks:
  ced-network:
    driver: bridge
